---
- hosts: all
  become: yes
  become_user: Administrator
  become_method: runas
  gather_facts: no
  
  tasks:
    - name: Install SQL Server Management Studio using Chocolatey
      win_chocolatey:
        name: sql-server-management-studio
        state: present