---
- hosts: localhost
  become: yes
  become_user: Administrator
  become_method: runas
  gather_facts: no

  tasks:
  - name: Run Windows Update
    ansible.windows.win_updates:
      category_names: '*'
      reboot: true
    delegate_to: localhost