---
- hosts: all
  become: true
  become_user: Administrator
  become_method: runas
  gather_facts: no

  tasks:
  - name: Run Windows Update
    ansible.windows.win_updates:
      category_names: '*'
      #become: true
      #become_method: runas
      #become_user: Administrator
      reboot: true
    #delegate_to: localhost