---
- hosts: all
  become: yes
  become_user: Administrator
  become_method: runas
  gather_facts: no

  tasks:
    - name: Run Windows Update
      win_updates:
        categories:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - Updates
        #state: installed
        reboot: yes
        reboot_timeout: 3600