---
- hosts: all
  become: yes
  become_user: Administrator
  become_method: runas
  gather_facts: no

  tasks:
    - name: Run Windows Update
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - Updates
        state: installed
      register: win_update_result
      ignore_errors: true

    - name: Reboot if required
      ansible.windows.win_reboot:
      when: win_update_result.reboot_required is defined and win_update_result.reboot_required

    - name: Wait for system to reboot
      ansible.windows.win_wait_for:
        state: restarted
        timeout: 300
      when: win_update_result.reboot_required is defined and win_update_result.reboot_required