---
- hosts: all
  become: yes
  become_user: Administrator
  become_method: runas
  gather_facts: no

  tasks:
    - name: Run Windows Update
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - Updates
        state: installed
      register: win_update_result

    - name: Check if a reboot is required
      ansible.windows.win_reboot:
      register: reboot_status
      ignore_errors: true
      changed_when: false

    - name: Reboot if required
      ansible.windows.win_reboot:
      when: reboot_status.reboot_required

    - name: Wait for system to reboot
      ansible.windows.win_wait_for:
        state: restarted
        timeout: 300
      when: reboot_status.reboot_required