---
- hosts: all
  become: yes
  become_user: Administrator
  become_method: runas
  gather_facts: no

  tasks:
    - name: Run Windows Update
      win_updates:
      category_names: '*'
      reboot: true