---
- hosts: windows_servers  # Target your Windows servers
  become: yes
  become_user: Administrator
  become_method: runas

  tasks:
    - name: Install Windows Updates
      win_updates:
        categories:  # Optional - specify categories (e.g., CriticalUpdates, SecurityUpdates)
          - SecurityUpdates
        reboot: yes  # Automatically reboot if required
        reboot_timeout: 3600  # Wait up to an hour for reboot to complete

    - name: Ensure Windows is back online after reboot (if applicable)
      wait_for_connection:
        timeout: 300  # Wait up to 5 minutes