---
- hosts: all
  become: yes
  become_user: Administrator
  become_method: runas
  gather_facts: no

  tasks:
    - name: Run Windows Update
      ansible.windows.win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - Updates
        state: installed
      register: win_update_result

    - name: Reboot if updates require it
      ansible.windows.win_reboot:
      when: win_update_result.reboot_required

    - name: Wait for system to reboot
      ansible.windows.win_wait_for:
        state: restarted
        timeout: 300
