---
- hosts: all
  become: yes
  become_user: Administrator
  become_method: runas
  gather_facts: no
  
  tasks:
    - name: Install Chocolatey Windows Update Extension using Chocolatey
      win_chocolatey:
        name: chocolatey-windowsupdate.extension
        state: present
