---
- hosts: all
  become: yes
  become_user: Administrator
  become_method: runas
  gather_facts: no

  tasks:
    - name: Install all updates and reboot as many times as needed
      ansible.windows.win_updates:
        category_names: '*'
        reboot: true