---
- hosts: all
  become: yes
  become_user: Administrator
  become_method: runas
  gather_facts: no

  tasks:
    - name: Run Windows Update
      win_updates:
        category_names:
          - CriticalUpdates
          - SecurityUpdates
          - UpdateRollups
          - Updates
        state: installed

    - name: Check if reboot is required
      win_reboot:
        check_pending: yes
      register: reboot_required

    - name: Reboot if required
      win_reboot:
        reboot_timeout: 600
      when: reboot_required.pending_reboot

    - name: Ensure Windows is back online after reboot (if applicable)
      wait_for_connection:
        timeout: 300