---
- name: Get OS Version on Linux
  hosts: RHEL_9.2
  gather_facts: yes
  tasks:
    - name: Retrieve OS Version
      shell: "cat /etc/os-release | grep PRETTY_NAME
      register: os_version_output

    - name: Display OS Version
      debug:
        msg: "Operating System version is {{ os_version_output.stdout }}"
