---
- name: Get OS Version on Linux
  hosts: all
  gather_facts: yes
  tasks:
    - name: Retrieve OS Version
      shell: "cat /etc/os-release | grep PRETTY_NAME
      register: os_version_output
      changed_when: false  # Mark the task as unchanged

    - name: Display OS Version
      debug:
        msg: "Operating System version is {{ os_version_output.stdout }}"
