---
- name: Display Linux hostname
  hosts: your_target_group_or_host
  tasks:
    - name: Get hostname
      shell: /bin/hostname
      register: hostname_output

    - name: Print hostname
      debug:
        msg: "The hostname is {{ hostname_output.stdout }}"
