---
- name: Install MySQL on Red Hat Enterprise Linux
  hosts: all 
  become: yes

  tasks:
    - name: Install MySQL Server
      dnf:
        name: mysql-server
        state: present
     # register: mysql_install_result

    - name: Debug message for MySQL installation status
      debug:
        msg: "MySQL installation on process.."

    - name: Start MySQL service
      service:
        name: mysqld
        state: started
        enabled: yes
     # register: mysql_service_result

    - name: Debug message for MySQL service status
      debug:
        msg: "MySQL service installation successfully."
