---
- name: Clone VM from a template
  hosts: localhost
  gather_facts: no
  vars:
    vcenter: "192.168.137.250"
    username: "administrator@vsphere.local"
    password: "P@ssw0rd"
    datacenter: "local"
    datastore: "vCenter"

  tasks:
    - name: Clone VM from template
      community.vmware.vmware_guest:
        hostname: "{{ vcenter }}"
        username: "{{ username }}"
        password: "{{ password }}"
        validate_certs: no
        datacenter: "{{ datacenter }}"
        datastore: "{{ datastore }}"
        folder: "/{{ datacenter }}/vm"
        name: "{{ vm_name }}"
        template: "{{ template_name }}"
        state: present
        hardware:
          memory_mb: "{{ memory_mb }}"
          num_cpus: "{{ num_cpus }}"
          num_cpu_cores_per_socket: "{{ num_cpu_cores_per_socket }}"
        wait_for_ip_address: yes
      delegate_to: localhost