---
- hosts: localhost
  #vars:
    #vcenter: "172.18.0.60"
    #username: "administrator@vsphere.local"
    #password: "xP@ssw0rd@123"
  tasks:

    - name: Create RHEL VM
      community.vmware.vmware_guest:
        hostname: "{{ vcenter_hostname }}"
        username: "{{ vcenter_username }}"
        password: "{{ vcenter_password }}"
        folder: "/{{ vcenter_datacenter }}/vm"
        name: "{{ vm_name }}"
        state: poweredon
        guest_id: trhel8_64Guest
        disk:
    - size_gb: 50
      type: thin
      datastore: datastore1
      hardware:
      memory_mb: "{{ memory_mb }}"
      num_cpus: "{{ num_cpus }}"
      num_cpu_cores_per_socket: "{{ num_cpu_cores_per_socket }}"
      scsi: paravirtual
      networks:
    - name: VM Network
      #mac: aa:bb:dd:aa:00:14
      #ip: 10.10.10.100
      #netmask: 255.255.255.0
      device_type: vmxnet3
    #wait_for_ip_address: true
    #wait_for_ip_address_timeout: 600
  delegate_to: localhost
  register: deploy_vm