---
- hosts: localhost
  gather_facts: no
  #vars:
    #vcenter: "172.18.0.60"
    #username: "administrator@vsphere.local"
    #password: "xP@ssw0rd@123"
  tasks:

    - name: Create RHEL VM
      community.vmware.vmware_guest:
        hostname: "172.18.0.60"
        username: "administrator@vsphere.local"
        password: "xP@ssw0rd@123"
        validate_certs: no
        datacenter: "Datacenter"
        folder: "/Datacenter/vm/"
        name: "vmansible"
        state: poweredoff
        guest_id: rhel8_64Guest
        disk:
        - size_gb: 40
          type: thin
          datastore: "SimpliVity-Datastore"
        hardware:
          memory_mb: "4096"
          num_cpus: "4"
          num_cpu_cores_per_socket: "4"
          scsi: paravirtual   
        cdrom:
          - controller_number: 0
            unit_number: 0
            state: present
            type: iso
            iso_path: "[SimpliVity-Datastore] ISO/rhel-baseos-9.1-x86_64-dvd.iso"
        networks:
          - name: VM Network
            dvswitch_name: "DSwitch-Simplivity"
            vlan: 2005
            type: dhcp
            #mac: aa:bb:dd:aa:00:14
            #ip: 10.10.10.100
            #netmask: 255.255.255.0
            device_type: vmxnet3
        wait_for_ip_address: true
        wait_for_ip_address_timeout: 600
        customization:
          hostname: vmansible
          dns_servers:
            - 8.8.8.8
          timezone: UTC
          timezone_utc: yes
          domain: example.com
          kickstart: |
            #platform=x86, AMD64, or Intel EM64T
            #version=DEVEL
            # Install OS instead of upgrade
            install
            # Keyboard layouts
            keyboard 'us'
            # Root password
            rootpw --iscrypted $6$.3Oog3q9GGVlImSx$saBskD8SmnXIDm3HnldLN8bssIFP4q1OQv4EqM4yKw8cn0otk96Ceqr5AMj2qCt7dz0of57pvX6JvQekIXxiK0
            # System language
            lang en_US.UTF-8
            # Firewall configuration
            firewall --disabled
            # System authorization information
            auth --useshadow --passalgo=sha512
            # Use CDROM installation media
            cdrom
            # Use text mode install
            text
            # System bootloader configuration
            bootloader --location=mbr
            # Clear the Master Boot Record
            zerombr
            # Partition clearing information
            clearpart --all --initlabel
            # Disk partitioning information
            part / --fstype="xfs" --grow --size=1
            # Reboot after installation
            reboot
            # Network information
            network  --bootproto=dhcp --device=ens192 --onboot=on
            # Run the Setup Agent on first boot
            firstboot --enable
            # SELinux configuration
            selinux --disabled
            # System services
            services --enabled="chronyd"
            # System commands
            %packages
            @^minimal
            %end
      delegate_to: localhost
      register: deploy_vm

    - name: Debug deploy_vm
      debug:
        var: deploy_vm