---
- hosts: localhost
  gather_facts: no
  #vars:
    #vcenter: "172.18.0.60"
    #username: "administrator@vsphere.local"
    #password: "xP@ssw0rd@123"
  tasks:

    - name: Deploy Virtual Machine from template in content library with PowerON State
      community.vmware.vmware_content_deploy_template:
        hostname: "172.18.0.60"
        username: "administrator@vsphere.local"
        password: "xP@ssw0rd@123"
        template: Rrhel-9.2-x86-dvd
        content_library: rhel-9.2-x86-dvd
        datastore: Datacenter
        folder: vm
        datacenter: Datacenter
        name: RHELVM
      state: poweredon
  delegate_to: localhost